# Generated by Django 6.1 on 2026-09-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_purchase_return_book_cost_price_book_edition_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="Return",
        ),
    ]
