# Generated by Django 6.1 on 2026-09-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                ("payment_status", models.CharField(max_length=50)),
                ("expected_delivery", models.DateField(blank=True, null=True)),
                ("order_status", models.CharField(max_length=50)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
