# Generated by Django 6.1 on 2026-09-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="details",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
