# Generated by Django 6.1 on 2026-09-22 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_hiring_date_user_middle_name_user_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilechangerequest",
            name="avatar_choice",
        ),
        migrations.RemoveField(
            model_name="profilechangerequest",
            name="profile_picture",
        ),
        migrations.AddField(
            model_name="profilechangerequest",
            name="contact_numbers",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profilechangerequest",
            name="middle_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name="ContactNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_numbers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
