# Generated by Django 6.1 on 2026-09-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_date", models.DateField()),
                ("return_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("return_type", models.CharField(max_length=50)),
                ("reason", models.TextField()),
                ("return_status", models.CharField(max_length=50)),
            ],
        ),
    ]
