# Generated by Django 6.1 on 2026-09-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retur", "0002_return_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="return",
            name="return_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
