# Generated by Django 6.1 on 2026-09-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retur", "0003_return_return_quantity"),
        ("sales", "0002_saleitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="return",
            name="sale_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returns",
                to="sales.saleitem",
            ),
        ),
    ]
