# Generated by Django 6.1 on 2026-09-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retur", "0004_return_sale_item"),
        ("sales", "0002_saleitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_date", models.DateField()),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_batches",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="return",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="retur.returnbatch",
            ),
        ),
    ]
