# Generated by Django 6.1 on 2026-08-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="created_at",
        ),
    ]
